config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home', to: 'static_pages#home', as: 'home'
  get 'useful_resources/new'
  get 'useful_resources/index'
  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end
  resources :useful_resources

  root "blog_posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content
  scope :sorted, -> { order(created_at: :desc) }
  validates :title, presence: true
  validates :content, presence: true

end

app/models/useful_resource.rb
class UsefulResource < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later
    redirect_to edit_blog_post_path(@blog_post), notice: "Cover image was successfully removed."
  end

  private

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  # GET /blog_posts or /blog_posts.json
  def index
    @blog_posts = BlogPost.all.sorted
    @pagy, @blog_posts = pagy(@blog_posts, items: 10)
    rescue Pagy::OverflowError
      # redirect_to root_path(page: 1)
      params[:page] = 1
    retry
  end

  # GET /blog_posts/1 or /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts or /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully created." }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1 or /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1 or /blog_posts/1.json
  def destroy
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Blog post was successfully destroyed.", status: :see_other}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :cover_image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end
end

app/controllers/useful_resources_controller.rb
class UsefulResourcesController < ApplicationController
  def new
  end

  def index
    @useful_resources = UsefulResource.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/useful_resources_helper.rb
module UsefulResourcesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_blog_post.html.erb
<div id="<%= dom_id blog_post %>">

  <%= image_tag blog_post.cover_image.variant(resize_to_limit: [200, 200]) if blog_post.cover_image.present? %>

  <div class="bg-gray-300 font-semibold capitalize">
    <h2>
      <%= link_to blog_post.title, blog_post %>
    </h2>
  </div>


  <div class="bg-blue-100 p-1">
  <p>
    <%= blog_post.content %>
  </p>
  </div>


</div>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if blog_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :cover_image, style: "display: block" %>
    <% if blog_post.cover_image.present? %>
      <%= image_tag blog_post.cover_image, class: "w-1/4" %>
      <%= link_to "Remove cover image", blog_post_cover_image_path(blog_post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
    <%= form.file_field :cover_image %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Show this blog post", @blog_post %> |
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="bg-gray-300 p-3">Blog posts</h1>

<div id="blog_posts", class="grid grid-cols-2 gap-4 md:grid-col-2 lg:grid-cols-3 xl:grid-cols-4">
  <% @blog_posts.each do |blog_post| %>
    <div class="shadow-md shadow-blue-200 blur-sm hover:blur-none brightness-50 hover:brightness-100
    p-1 truncate ...">
      <%= render blog_post %>
    </div>

  <% end %>
</div>

<%= link_to "New blog post", new_blog_post_path %>

<% if @pagy.count > @pagy.items %>
  <div class="my-10">
   <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>New blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Back to blog posts", blog_posts_path %>
</div>

app/views/blog_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_post %>

<div>
  <%= link_to "Edit this blog post", edit_blog_post_path(@blog_post) %> |
  <%= link_to "Back to blog posts", blog_posts_path %>

  <%= button_to "Destroy this blog post", @blog_post, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<h3>footer</h3>

app/views/layouts/_header.html.erb
<%= link_to "Useful Resources", useful_resources_path %>
<%= link_to "Home", home_path %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExperimentingTailwindCss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose p-4 mx-auto w-screen">
    <%= render "layouts/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div id="container"></div>
<script type="module">

import "d3.js";
// Declare the chart dimensions and margins.
const width = 640;
const height = 400;
const marginTop = 20;
const marginRight = 20;
const marginBottom = 30;
const marginLeft = 40;

// Declare the x (horizontal position) scale.
const x = d3.scaleUtc()
    .domain([new Date("2023-01-01"), new Date("2024-01-01")])
    .range([marginLeft, width - marginRight]);

// Declare the y (vertical position) scale.
const y = d3.scaleLinear()
    .domain([0, 100])
    .range([height - marginBottom, marginTop]);

// Create the SVG container.
const svg = d3.create("svg")
    .attr("width", width)
    .attr("height", height);

// Add the x-axis.
svg.append("g")
    .attr("transform", `translate(0,${height - marginBottom})`)
    .call(d3.axisBottom(x));

// Add the y-axis.
svg.append("g")
    .attr("transform", `translate(${marginLeft},0)`)
    .call(d3.axisLeft(y));

// Append the SVG element.
container.append(svg.node());

</script>

app/views/useful_resources/_my_card.html.erb
<div class="group db-white rounded-2xl shadow-lg p-4">
  <%=image_tag 'my_card.png', class: 'group-hover:scale-110 transform transition duration-300 ease-in-out
  rounded-2xl shadow-lg h-40 w-40' %>
  <div>
    <p class="font-semibold"
     >Masashi</p>
    <p> Card is a simple app that allows you to create a digital business card.</p>
    <div>
      <p class="group-hover:scale-110 transform transition duration-300 ease-in-out">
      <%= link_to 'https://my-card-app.herokuapp.com/', 'https://my-card-app.herokuapp.com/' %></p>
    </div>
  </div>
</div>

app/views/useful_resources/_useful_resource.html.erb
<div>
  <div>
    <h2><%= useful_resource.title %></h2>
    <p><%= useful_resource.description %></p>
    <div>
      <p><%= useful_resource.url %></p>
    </div>
  </div>
</div>

app/views/useful_resources/index.html.erb
<%= link_to 'New Useful Resource', new_useful_resource_path %>

<%= icon('fab', 'font-awesome', 'Who', id: 'my-icon', class: 'fa-beat')%>

<div>
  <svg class="w-6 h-6 animate-spin"  viewBox="0 0 24 24">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
  </svg>
</div>




<div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
<% 10.times do %>
  <div class="saturate-150 blur-xl">
    <%= render partial:'my_card' %>
  </div>

<% end %>
</div


<% @useful_resources.each do |useful_resource| %>
  <%= render useful_resource, useful_resource: useful_resource %>
<% end %>

app/views/useful_resources/new.html.erb
<div>
  <h1 class="font-bold text-4xl">UsefulResources#new</h1>
  <p>Find me in app/views/useful_resources/new.html.erb</p>
</div>